"""
Django settings for DetectoresMetales project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

"""
Archivo de configuracion. Por defecto, Django te recomienda que configures 
unos pocos de parametros (debug, aplicaciones, middleware, base de 
datos, ...), pero puede contener otras muchas configuraciones. Todas 
las que aqui aparecen: global_settings (todas documentadas) y por supuesto 
puedes crear las que necesites. El unico requisito es que tienen que ser 
variables en mayusculas.

Siempre se debe de importar usando lo siguiente:

 from django.conf import settings (hecho)

Nunca debemos importarlo usando algo como lo siguiente, ya que de esta 
manera solo obtendriamos las configuraciones sobrescritas, pero no las 
no sobrescritas.

 from MI_PROYECTO import settings
"""


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
    # standard de python
from django.conf import settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        #ruta del proyecto

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zfy8$l2k%juf3$v)6&0ewxgx^%&u%@5)w2c$@k#fsfrin1($!g'
        # debe cambiarse

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
        # muestra luego errores en web

ALLOWED_HOSTS = []  # como proxy


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',          # requiere ->    pip install django-bootstrap3
    'DetectoresMetales.BBDD',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'DetectoresMetales.middleware.No404Middleware',
#    'DetectoresMetales.middleware.nombreClase',
#    en ruta proyecto/middleware.py, en este caso porque aplicable a todo el proyecto
)

ROOT_URLCONF = 'DetectoresMetales.urls'  
        # el principal

TEMPLATES = [  # nueva en 1.8
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # otros motores de plantillas -> jinja2
        'DIRS': [os.path.join(BASE_DIR, 'DetectoresMetales', 'templates')], 
        # lo he creado
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'DetectoresMetales.context_processors.blog',
#               'DetectoresMetales.context_processors.nombreFunc',
#                en ruta proyecto/context_processors.py, en este caso porque aplicable a todo el proyecto
#                función llamada con templatetags
            ],
        },
    },
]

WSGI_APPLICATION = 'DetectoresMetales.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3', 
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',         
        'NAME': 'DetectoresMetales',
        'USER': 'el_usuario',
        'PASSWORD': 'la_contrasenia',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'UTC'

USE_I18N = True  # internacionalizacion

USE_L10N = True  # localizacion

USE_TZ = True    # timezone


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
    # referencia lugares donde debe buscar
STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'DetectoresMetales', 'static') ]
    # la sobreescribe tras consultar existencia en
    #   proyecto GitHub -> django/django/conf/global_settings.py


# ESPECIFICAS

# usada por la paginacion en expedientes_list.html
PAGINATION_PAGES = 6

# usada por el context_processor.py y desde la plantilla inc.menu.html
BLOG_URL = 'http://blog.example.com/foo'
